permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
paginate: 5
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed
theme: jekyll-theme-so-simple
masthead_title: Home
title: "Anna Robson"
logo: "images/anna_robson_square.jpg"
description: "Strategic Leader, Business Transformation Expert, and Executive Coach"
masthead_bio: "I'm a strategic business leader blending law, ethics, and data-driven strategy to drive growth, partnerships, and impactful change."


category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

search: true

author:
  name: "Anna Robson"
  location: "Toronto, ON, Canada"
  picture: 
  bio: "Anna Robson is a strategic leader with a unique blend of legal expertise, ethical insight, and data-driven strategy. With a proven track record in business transformation, she excels in driving growth and fostering impactful partnerships. As an executive coach, Anna empowers leaders to navigate complex challenges and achieve sustainable success."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/"
    - label: "Contact Me"
      icon: "fas fa-fw fa-envelope-square"
      url: "/contact/"

footer_links:
  - title: "Contact Me"
    icon: "fas fa-fw fa-envelope-square"
    url: "/contact/"

url: "https://www.annarobson.com"
feed:
  path: feed.xml

defaults:
  # _posts
  defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

locale: en-US

copyright: 2015-2025 Anna Robson

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
